language: java
install: true

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - alias gradle="./gradlew --stacktrace"

script:
  - gradle build
  - gradle verifyPlugin
  - gradle buildPlugin